services:
  - type: web
    name: customer-churn-app
    env: python
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .."
    startCommand: "python api/main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
